resolver: lts-9.14

packages:
- '.'

extra-deps:
- containers-0.5.10.2
- cborg-0.2.0.0
- cryptonite-0.24
- serialise-0.2.0.0
- stm-2.4.5.0

flags:
  serialise:
    newtime15: true

extra-package-dbs: []
